import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import RestartButton from "@/components/RestartButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "flex flex-col text-foreground bg-background min-h-screen w-screen")}>
                <nav className="sticky top-0 flex flex-row items-center w-full bg-foreground/90 text-background shadow-sm backdrop-blur p-4">
                    <h1 className="text-3xl"><strong>Movie</strong> Meter</h1>
                    <span className="flex-grow"></span>
                    <RestartButton />
                </nav>
                <div className="flex flex-col flex-grow justify-center items-center p-10">
                    {children}
                </div>
            </body>
        </html>
    );
}
